name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: phpcs
    
    - name: Install WordPress Standards
      run: |
        # Install required packages
        composer global require squizlabs/php_codesniffer
        composer global require wp-coding-standards/wpcs
        composer global require dealerdirect/phpcodesniffer-composer-installer
        
        # Set installed paths
        phpcs --config-set installed_paths $(composer global config home)/vendor/wp-coding-standards/wpcs
        
        # Verify installation
        phpcs -i
        
    - name: Basic PHP Syntax Check
      run: find . -name '*.php' -not -path './vendor/*' -exec php -l {} \;
    
    - name: WordPress Standards Check
      run: phpcs --standard=WordPress --extensions=php --ignore=vendor/ .
