name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      id: checkout
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Check PHP syntax
      run: |
        find . -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l || exit 1
    
    - name: Get commit message
      id: commit-message
      run: |
        MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
        MESSAGE="${MESSAGE//'%'/'%25'}"
        MESSAGE="${MESSAGE//$'\n'/'%0A'}"
        MESSAGE="${MESSAGE//$'\r'/'%0D'}"
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
    
    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "PHP Syntax Check Failed in ${{ github.repository }}"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions
        body: |
          Commit: ${{ steps.commit-message.outputs.message }}
          Author: ${{ github.actor }}
          SHA: ${{ github.sha }}
          Repository: ${{ github.repository }}
          
          PHP syntax check failed!
          
          View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
