name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP Environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: phpcs
    
    - name: Configure Composer Permissions
      run: |
        # Allow required plugins
        composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        composer global config --no-plugins allow-plugins.squizlabs/php_codesniffer true
        
    - name: Install WordPress Coding Standards
      run: |
        # Clear composer cache (fixed version without --all)
        composer global clear-cache
        
        # Install requirements
        composer global require \
          squizlabs/php_codesniffer \
          wp-coding-standards/wpcs \
          dealerdirect/phpcodesniffer-composer-installer \
          phpcsstandards/phpcsextra \
          phpcsstandards/phpcsutils \
          --ignore-platform-reqs
        
        # Configure paths
        phpcs --config-set installed_paths $(composer global config home)/vendor/wp-coding-standards/wpcs
        
        # Verify installation
        phpcs -i
        
    - name: Run Basic PHP Syntax Check
      run: find . -name '*.php' -not -path './vendor/*' -exec php -l {} \;
    
    - name: Run WordPress Standards Check
      run: phpcs --standard=WordPress --extensions=php --ignore=vendor/ .
