name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Check PHP syntax
      run: |
        set -e  # Exit immediately if any command fails
        ERROR_FOUND=false
        
        # Check each PHP file
        while IFS= read -r -d '' file; do
          if ! php -l "$file"; then
            echo "::error file=$file::PHP syntax error found"
            ERROR_FOUND=true
          fi
        done < <(find . -name '*.php' -not -path './vendor/*' -print0)
        
        if $ERROR_FOUND; then
          exit 1  # This will make the workflow fail
        fi
