name: PHP Syntax Check
on: [push, pull_request]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Check PHP syntax
      run: |
        find . -name '*.php' -not -path './vendor/*' -exec php -l {} \; || exit 1
    
    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "PHP Syntax Check Failed in ${{ github.repository }}"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions
        body: |
          PHP syntax check failed in commit ${{ github.sha }}
          View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
